name: Build Kernel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Update APT
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf
    
    - name: Getting Informations
      id: info
      run: make git
      
    - name: Getting Advanced Informations
      id: adv_info
      run: make kernelgit
      
    - name: Getting Commit-Hash
      id: commit
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - name: Getting Build Number
      id: build_num
      run: ./scripts/build-git.sh ${{ github.run_number }}
    
    - name: Setting Variable
      id: variable
      run: echo ::set-output name=global-ver::${{ steps.info.outputs.version }}.${{ steps.info.outputs.patch }}.${{ steps.info.outputs.subversion }}${{ steps.info.outputs.extra }}-${{ steps.build_num.outputs.build-number }}_${{ steps.commit.outputs.sha_short }}
    
    - name: Printing Debugging-Text
      id: debug
      run: echo ${{ steps.variable.outputs.global-ver }}, Kernel ${{ steps.adv_info.outputs.kernel }}
            
    - name: make clean
      run: make clean
      
    - name: Copy Default Configuration
      run: cp ./markustieger.config ./.config
      
    - name: Build Kernel with DEB-Packages
      run: make deb-pkg
      
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.variable.outputs.global-ver }}
        release_name: ${{ steps.variable.outputs.global-ver }}
          #body: |
          #  Changes in this Release
          #  - First Change
          #  - Second Change
        draft: false
        prerelease: false
        
    - name: Upload Kernel Image
      id: upload_image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../linux-image-${{ steps.adv_info.outputs.kernel }}_${{ steps.adv_info.outputs.kernel }}-1_amd64.deb
        asset_name: linux-image-${{ steps.adv_info.outputs.kernel }}_${{ steps.adv_info.outputs.kernel }}-1_amd64.deb
        asset_content_type: application/vnd.debian.binary-package
      continue-on-error: true
      
    - name: Upload Kernel BZ
      id: upload_bz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./arch/x86_64/boot/bzImage
        asset_name: kernel-${{ steps.adv_info.outputs.kernel }}.bz
        asset_content_type: application/x-bzip
      continue-on-error: true
      
    - name: Upload Kernel Headers
      id: upload_headers
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../linux-headers-${{ steps.adv_info.outputs.kernel }}_${{ steps.adv_info.outputs.kernel }}-1_amd64.deb
        asset_name: linux-headers-${{ steps.adv_info.outputs.kernel }}_${{ steps.adv_info.outputs.kernel }}-1_amd64.deb
        asset_content_type: application/vnd.debian.binary-package
      continue-on-error: true
      
    - name: Upload Lib
      id: upload_lib
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../linux-libc-dev_${{ steps.adv_info.outputs.kernel }}-1_amd64.deb
        asset_name: linux-libc-dev_${{ steps.adv_info.outputs.kernel }}-1_amd64.deb
        asset_content_type: application/vnd.debian.binary-package
      continue-on-error: true
      
    - name: Upload Info
      id: upload_info
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../linux-upstream_${{ steps.adv_info.outputs.kernel }}-1_amd64.buildinfo
        asset_name: linux-upstream_${{ steps.adv_info.outputs.kernel }}-1_amd64.buildinfo
        asset_content_type: text/plain
      continue-on-error: true
      
    - name: Upload Changes
      id: upload_changes
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../linux-upstream_${{ steps.adv_info.outputs.kernel }}-1_amd64.changes
        asset_name: linux-upstream_${{ steps.adv_info.outputs.kernel }}-1_amd64.changes
        asset_content_type: text/plain
      continue-on-error: true
      
    - name: Upload Diff GZ
      id: upload_diff
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../linux-upstream_${{ steps.adv_info.outputs.kernel }}-1.diff.gz
        asset_name: linux-upstream_${{ steps.adv_info.outputs.kernel }}-1.diff.gz
        asset_content_type: application/gzip
      continue-on-error: true
      
    - name: Upload Orig Tar
      id: upload_orig
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../linux-upstream_${{ steps.adv_info.outputs.kernel }}.orig.tar.gz
        asset_name: linux-upstream_${{ steps.adv_info.outputs.kernel }}.orig.tar.gz
        asset_content_type: application/x-tar
      continue-on-error: true
      
    - name: Upload DSC
      id: upload_dsc
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../linux-upstream_${{ steps.adv_info.outputs.kernel }}-1.dsc
        asset_name: linux-upstream_${{ steps.adv_info.outputs.kernel }}-1.dsc
        asset_content_type: text/plain
      continue-on-error: true
