name: Build Kernel Deb-Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Update APT
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf
    
    - name: make clean
      run: make clean
      
    - name: Copy Default Configuration
      run: cp ./markustieger.config ./.config
      
    - name: Build Kernel DEB-Packages
      run: make deb-pkg
      
    - name: Copy DEB-Packages
      run: mkdir deb && cp /usr/src/*.deb ./deb
      
    - name: List Debs
      run: ls ./deb
