name: Build Kernel Deb-Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Add APT Repositories
      run: sudo echo "deb-src http://archive.ubuntu.com/ubuntu disco main" >> /etc/apt/sources.list && sudo echo "deb-src http://archive.ubuntu.com/ubuntu disco-updates main" >> /etc/apt/sources.list
    - name: Update APT
      run: sudo apt-get update
    - name: Prepare Environment
      run: sudo apt-get build-dep linux linux-image-$(uname -r)
    - name: Install Dependencies
      run: sudo apt-get install libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf
    
    - name: make clean
      run: make clean
      
    - name: Copy Default Configuration
      run: cp ./markustieger.config ./.config
      
    - name: Build Kernel DEB-Package
      run: make deb-pkg
      
    - name: List Files
      run: ls
